import { Inter } from "next/font/google";
import "./globals.css";
import { RecurrenceProvider } from "../../context/RecurrenceProvider"; // Adjust path as needed

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Date Picker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecurrenceProvider>{children}</RecurrenceProvider>
      </body>
    </html>
  );
}
